version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    restart: always
    command:
      - redis-server
      - --requirepass
      - autogen_api
  postgresql:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: always

  # example:
  #   image: justarchi/archisteamfarm
  #   container_name: asf
  #   volumes:
  #     - /home/wei/asf/config:/app/config
  #   ports:
  #     - "1242:1242"
  #   restart: always
