name: 'OpenCommit Action'

on:
  push:
    branches:
      - master
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit

    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        env:
          # set openAI api key in repo actions secrets,
          # for openAI keys go to: https://platform.openai.com/account/api-keys
          # for repo secret go to: <your_repo_url>/settings/secrets/actions
          OCO_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          # customization
          OCO_OPENAI_MAX_TOKENS: 4096
          OCO_OPENAI_BASE_PATH: ''
          OCO_DESCRIPTION: postface a message with ~3 sentences description of the changes
          OCO_EMOJI: true
          OCO_MODEL: gpt-3.5-turbo-16k
          OCO_LANGUAGE: en
          OCO_PROMPT_MODULE: conventional-commit
